### ISSUE TITLE
FLOW10 - Create new flows

### ISSUE THREAD

**Issue by jannunzi** [jannunzi/wax#30]
clicking on the plus of the flow navigates to new flow view where you can name the new flow. clicking on ok saves the flow and navigates back to the list of flows where the new flow appears.

<img width="501" alt="screen shot 2017-03-20 at 10 37 42 pm" src="https://cloud.githubusercontent.com/assets/1682522/24130257/e113d392-0dbd-11e7-8d6d-1ddf5c37348c.png">

**Comment by nischaym** [comment]
https://github.com/jannunzi/wax/pull/38
