### ISSUE TITLE
USER-4 - Create user schema, model, service

### ISSUE THREAD

**Issue by jannunzi** [jannunzi/wax#5]
/wax/ide/services/user.service.server.js
import from CS5610 assignments

/wax/ide/models/user/user.model.server.js
createUser, findUserById, findUserByCredentials, findUserByUsername, all the CRUD
reuse code from assignment
import from assignment

/wax/ide/models/user/user.schema.server.js
username, password, firstName, lastName, email
import from assignments

**Comment by nischaym** [comment]
PR created
